input: Adjust reported ID_SW_MAX after ANC removal
Removing ANC support from the kernel, which already ships a customized
version of input.h from the OEM, messed up the entries for
INPUT_DEVICE_ID_* since some were allocated for that feature. Adjust
INPUT_DEVICE_ID_SW_MAX to match SW_MAX for our values.

Fixes the following build issue:

/tmp/src/android/kernel/sony/sm8150/include/linux/input.h:236:2: error: "SW_MAX and INPUT_DEVICE_ID_SW_MAX do not match"
  236 | #error "SW_MAX and INPUT_DEVICE_ID_SW_MAX do not match"
      |  ^

Fixes: 4ea7f7d4e73e4131081f ("Revert "ANDROID: ALSA: jack: Update supported jack switch types"")
Signed-off-by: voidanix <voidanix@keyedlimepie.org>